---
title: "AllCauseMortalityPost7_30"
author: "Ben Szeto"
date: "2024-07-30"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, loading libraries}
library(tidyverse)
library(knitr)
library(plotly)
library(ggeffects)
library(ggformula)
library(ipumsr)
library(survival)
library(survminer)
library(table1)
```

```{r Ben Windows Paths}


ddi <- read_ipums_ddi("C:/Users/bszet/Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00029.xml")

data1 <- read_ipums_micro(ddi)

ddi <- read_ipums_ddi("C:/Users/bszet/Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00027.xml")

data2 <- read_ipums_micro(ddi)

ddi <- read_ipums_ddi("C:/Users/bszet/Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00030.xml")

data3 <- read_ipums_micro(ddi)

```

```{r Ben Mac Path}

# ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00029.xml")
# 
# data1 <- read_ipums_micro(ddi)
# 
# ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00027.xml")
# 
# data2 <- read_ipums_micro(ddi)
# 
# ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00030.xml")
# 
# data3 <- read_ipums_micro(ddi)


```

```{r, data merging}
data1<-data1%>%#Selecting variables of interest from data1
  select(NHISPID, DIABETICAGE, DIAYRSAGO)

data3<-data3%>%#Selecting variables of interest from data3
  select(NHISPID, MORTDODY, MORTWT, MORTSTAT)

data<-merge(data1, data2, by="NHISPID")
data<-merge(data, data3, by="NHISPID")

```

```{r}
data%>%
  filter(!MORTDODY==9999)%>%
  select(MORTDODY)%>%
  arrange(desc(MORTDODY))

```

```{r, defining exposure time since DOB(This is what we use for expsoreu. underlying time scale cox)}
data<-data%>%
  mutate(exposure_birth=ifelse(
    MORTSTAT==1,
    MORTDODY-YEAR+AGE,#If dead, time ends at year of death
    2019-YEAR+AGE#If alive or NIU, time ends at 2019
    ))

```

```{r, defining exposure time since Diabetes Diagnosis}

data<-data%>%
  mutate(exposure_diabetes=ifelse(
    !DIABETICAGE==96 & !MORTDODY==9999,
    (AGE-DIABETICAGE)+(MORTDODY-YEAR),
    NA
  ))

```

```{r, data cleaning}
data<-data%>%
  mutate(racea=as_factor(RACEA))%>%
  mutate(mortstat=as_factor(MORTSTAT))%>%
  mutate(morthypr=as_factor(MORTHYPR))%>%
  mutate(sex=as_factor(SEX))%>%
  filter(racea%in%c("Chinese", "Asian Indian", "White", "Filipino"))%>% #selecting Chinese, Asian Indian, Filipino, and White
  filter(!BMI==0)%>% #filtering out extraneous BMIs
  filter(BMI<90)%>%
  filter(MORTELIG==1)%>%
  mutate(BMI_R_Cat=ifelse(racea=="White", 
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Whites
                                    BMI>=18.5 & BMI<25~"Normal Weight",
                                    BMI>=25 & BMI <30~"Overweight",
                                    BMI>=30~"Obese"),
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Asians (Considered all races not White)
                                    BMI>=18.5 & BMI<23~"Normal Weight",
                                    BMI>=23 & BMI <27.5~"Overweight",
                                    BMI>=27.5~"Obese")))#27.5 is obese for Asians
#mutate(CVD_MOR=ifelse(MORTUCODLD%in%c(1, 5), TRUE, FALSE))%>%
  
```

```{r education recoding}

data%>%
  select(EDUCREC2)%>%
  mutate(Education=as_factor(EDUCREC2))%>%
  ggplot()+
  geom_bar(aes(x=Education))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

data<-data%>%#recoding education
  filter(!EDUCREC2==0)%>%
  mutate(Education_recode=case_when(
    EDUCREC2%in%c(10,20,30,31,32,40,41)~"Did Not Complete High School",
    EDUCREC2==42~"High School Grad",
    EDUCREC2%in%c(50,51,52,53)~"Some College",
    EDUCREC2==54~"4 years college/Bachelor's degree",
    EDUCREC2==60~"Post Bachelor",
    EDUCREC2%in%c(96, 97,98,99)~"Unknown",
    TRUE~"Check Again"
  ))

data%>%
    ggplot()+
    geom_bar(aes(x=Education_recode, fill=racea), position="dodge")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

```{r smoking status recode}
data%>%
  ggplot()+
  geom_bar(aes(x=as_factor(SMOKESTATUS2)))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

data<-data%>%
  mutate(Smoking_recode=case_when(
    SMOKESTATUS2%in%c(10,11,12,13)~"Current Smoker",
    SMOKESTATUS2%in%c(20,40)~"Former Smoker",
    SMOKESTATUS2%in%c(30)~"Never Smoked",
    SMOKESTATUS2==90~"Unknown",
    TRUE~"Check Code"
  ))

data%>%
  ggplot()+
  geom_bar(aes(x=Smoking_recode))

```

```{r insurance coverage recode}
data%>%
  ggplot()+
  geom_bar(aes(x=as_factor(HINOTCOVE)))


data<-data%>%
  mutate(Insurance_recode=case_when(
    HINOTCOVE==1~"Covered",
    HINOTCOVE==2~"Uncovered",
    HINOTCOVE%in%c(7,8,9)~"Unknown",
    TRUE~"Check Code"
    
  ))

data%>%
  ggplot()+
  geom_bar(aes(x=Insurance_recode))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

```{r}

data<-data%>%
  mutate(USBorn_Recode=case_when(
         USBORN%in%c(10,11,12)~"Born Outside US",
         USBORN==20~"Born in US"))%>%
  mutate(USBorn_Recode=relevel(droplevels(as_factor(USBorn_Recode)), "Born in US"))

data%>%
  group_by(USBorn_Recode)%>%
  count()


```

```{r}
data%>%
  select(EARNINGS)%>%
  ggplot()+
  geom_bar(aes(x=as_factor(EARNINGS)))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


data<-data%>%
  mutate(Earnings_recode=as_factor(case_when(
    EARNINGS%in%c(0,97,98,99)~"NIU/Unknown",
    EARNINGS%in%c(1,2,3,4,5,6)~"Low Income ($1-$34,999)",
    EARNINGS%in%c(7,8,9,10)~"Middle Income($35,000-$74,999)",
    EARNINGS==11~"High Income(>$75,000)"
  )))%>%
  mutate(Earnings_recode=factor(Earnings_recode, levels=c("Low Income ($1-$34,999)", "Middle Income($35,000-$74,999)","High Income(>$75,000)","NIU/Unknown"  )))

data%>%
  ggplot()+
  geom_bar(aes(x=Earnings_recode))

data<-data%>%
  filter(!Earnings_recode=="NIU/Unknown")#Sample size goes down significantly when needing income information
```

```{r}
data_practice<-data%>%
  filter(!(HISPYN==2 & racea=="White"))%>%
  mutate(Diabetes_Lifetime=case_when(
    DIABETICEV==2|MORTDIAB==2~"Diabetic",
    DIABETICEV%in%c(0,7,8,9) & MORTDIAB==9~"Unknown/Not in Universe",
    TRUE~"Non-Diabetic"
  ))%>%
  filter(!Diabetes_Lifetime=="Unknown/Not in Universe")%>%
  mutate(Diabetes_Lifetime=as_factor(Diabetes_Lifetime))%>%
  mutate(Diabetes_Lifetime=droplevels(Diabetes_Lifetime))%>%
  mutate(Diabetes_Lifetime=relevel(Diabetes_Lifetime, "Non-Diabetic"))%>%
  mutate(Diab_ACM=case_when(
    MORTSTAT==1&Diabetes_Lifetime=="Diabetic"~"Diabetic Death",
    MORTSTAT==2~"Assumed Alive",
    TRUE~"Other Death"
  ))%>%
  #select(MORTELIG, MORTSTAT, Diabetes_Lifetime, Diab_ACM)%>%
  mutate(Diab_ACM_binary=ifelse(Diab_ACM=="Diabetic Death", TRUE, FALSE))%>%#Diabetes and dead (not necessisarily underlying cause)
  mutate(Diab_Und_ACM=ifelse(
    MORTSTAT==1 & MORTDIAB==2,
    TRUE,
    FALSE
  ))
  

# data_practice%>%
#   ggplot()+
#   geom_bar(aes(x=Diab_ACM_binary))
```

```{r}
data<-data%>%
  mutate(Diab_Und_ACM=ifelse(
    MORTSTAT==1 & MORTDIAB==2,
    TRUE,
    FALSE
  ))


data_practice%>%
  select(Diab_Und_ACM, MORTSTAT, MORTDIAB)
data
```

```{r}
data_practice%>%
  group_by(racea, Diab_ACM_binary)%>%
  summarise(
    n()
  )

data_practice%>%
  group_by(racea, Diab_Und_ACM)%>%
  summarise(
    n()
    
  )

```

```{r, cox model 1: All Mortality Diabetic}
cox_summary<-coxph(Surv(exposure_birth, Diab_ACM_binary) ~ racea + SEX + BMI_R_Cat:racea, data = data_practice)%>%
  summary()


cox_summary
coxcoefficients<-cox_summary$coefficients #removing empty coefficients
coxcoefficients[!is.na(coxcoefficients[,1]),] #removing empty coefficients


```

read: <https://socialsciences.mcmaster.ca/jfox/Books/Companion/appendices/Appendix-Cox-Regression.pdf>

```{r, cox model 2: Diabetes specific mortality}


data_practice%>%
  select(racea)


data_practice<-data_practice%>%
  mutate(sex=as_factor(SEX))%>%#removing extraneous levels
  mutate(sex=relevel(droplevels(sex), "Male"))%>%
  mutate(racea2=droplevels(racea))%>%
  mutate(racea2=relevel(racea2, "White"))%>%
  mutate(Smoking_recode=relevel(as_factor(Smoking_recode), "Never Smoked"))


cox_mod2<-coxph(Surv(exposure_birth, Diab_Und_ACM) ~ strata(racea2) + sex + BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_recode+USBorn_Recode, data = data_practice)


cox_summary<-summary(cox_mod2)
cox_summary
#Removing empty coefficients
# coxcoefficients<-cox_summary$coefficients #removing empty coefficients
# coxcoefficients[!is.na(coxcoefficients[,1]),] #removing empty coefficients


plot(survfit(cox_mod2), xlab="Years",ylab="Proportion Not Dead due to Diabetes", ylim=c(0.85,1), xlim=c(40,110), col=1:4)

legend("bottomleft", legend=levels(data_practice$racea2), col=1:4, lty=1)

#ggforest(cox_mod2, fontsize = 0.5)

```

```{r, model 3 ACM}

data_practice<-data_practice%>%
  mutate(Mort_recode=ifelse(MORTSTAT==1, TRUE, FALSE))%>%
  mutate(Mortality_Status=ifelse(MORTSTAT==1, "Presummed Dead", "Presummed Alive"))
  

cox_mod3<-coxph(Surv(exposure_birth, Mort_recode) ~ racea2 + sex + Diabetes_Lifetime:racea2+ BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_recode+USBorn_Recode, data = data_practice)


cox_summary<-summary(cox_mod3)
cox_summary


#plot(survfit(cox_mod3), xlab="Years",ylab="Proportion Not Dead due to Diabetes", ylim=c(0.75,1))



ggforest(cox_mod3, fontsize = 0.5)#Issues displaying interaction term


cox_mod3<-coxph(Surv(exposure_birth, Mort_recode) ~ strata(racea2) + sex + Diabetes_Lifetime:racea2+ BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_recode+USBorn_Recode, data = data_practice)

plot(survfit(cox_mod2), xlab="Years",ylab="Proportion Alive", ylim=c(0.85,1), xlim=c(40,110), col=1:4)

legend("bottomleft", legend=levels(data_practice$racea2), col=1:4, lty=1)
```


```{r, isolate diabetes interaction term for race}
data_practice<-data_practice%>%#manually making the interaction term
  mutate(Diabetes_Lifetime_Race=as_factor(ifelse(
    Diabetes_Lifetime=="Diabetic",
    case_when(
      racea2=="White"~"White Diabetic",
      racea2=="Asian Indian"~"Asian Indian Diabetic",
      racea2=="Filipino" ~"Filipino Diabetic",
      racea2=="Chinese"~"Chinese Diabetic",
      TRUE~"Check Code"),
    "Non-Diabetic"
  )))%>%
  mutate(Diabetes_Lifetime_Race=relevel(Diabetes_Lifetime_Race, "Non-Diabetic"))%>%
  mutate(Education_recode=factor(Education_recode, levels=c("High School Grad", "Did Not Complete High School","Some College", "4 years college/Bachelor's degree", "Post Bachelor", "Unknown")))%>%
  mutate(BMI_R_Cat=factor(BMI_R_Cat, levels=c("Normal Weight", "Underweight","Overweight", "Obese")))#Reordering levels



cox_mod3<-coxph(Surv(exposure_birth, Mort_recode) ~ racea2 + sex + Diabetes_Lifetime_Race+ BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_recode+USBorn_Recode, data = data_practice)


cox_summary<-summary(cox_mod3)
cox_summary




forrest_plot3<-ggforest(cox_mod3, fontsize = 1)


library(grDevices)
png(file="forestplot_mod3.png", width=1024, height=1024)
forrest_plot3
dev.off()



cox_mod3<-coxph(Surv(exposure_birth, Mort_recode) ~ strata(racea2) + sex + Diabetes_Lifetime_Race+ BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_recode+USBorn_Recode, data = data_practice)





plot(survfit(cox_mod3), xlab="Years",ylab="Proportion Alive", ylim=c(0.3,1), xlim=c(40,90))

```


```{r}
data_practice_diabetic<-data_practice%>%
  filter(Diabetes_Lifetime=="Diabetic")

cox_mod3<-coxph(Surv(exposure_birth, Mort_recode) ~ racea2 + sex + BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_recode+USBorn_Recode, data = data_practice_diabetic)


cox_summary<-summary(cox_mod3)
cox_summary




forrest_plot3<-ggforest(cox_mod3, fontsize = 1)#Issues displaying interaction term



library(grDevices)
png(file="forestplot_mod4_diabetes.png", width=1024, height=1024)
forrest_plot3


data_practice<-data_practice%>%#manually making the interaction term
  mutate(Diabetes_Over_Race=as_factor(ifelse(
    Diabetes_Lifetime=="Diabetic",
    case_when(
      racea2=="White"~"White Diabetic",
      racea2=="Asian Indian"~"Asian Indian Diabetic",
      racea2=="Filipino" ~"Filipino Diabetic",
      racea2=="Chinese"~"Chinese Diabetic",
      TRUE~"Check Code"),
    case_when(
      racea2=="White"~"White Non-diabetic",
      racea2=="Asian Indian"~"Asian Indian Non-diabetic",
      racea2=="Filipino" ~"Filipino Non-diabetic",
      racea2=="Chinese"~"Chinese Non-diabetic",
      TRUE~"Check Code")
  )))%>%
  mutate(Diabetes_Over_Race=factor(Diabetes_Over_Race, c("White Non-diabetic","Asian Indian Non-diabetic", "Filipino Non-diabetic", "Chinese Non-diabetic","White Diabetic",  "Asian Indian Diabetic", "Filipino Diabetic", "Chinese Diabetic" )))



cox_mod3<-coxph(Surv(exposure_birth, Mort_recode) ~ strata(Diabetes_Over_Race) + sex+ BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_recode+USBorn_Recode, data = data_practice)




plot(survfit(cox_mod3), xlab="Years",ylab="Proportion Alive", ylim=c(0,1), xlim=c(30,110), col=1:4, lty=c(1,1,1,1,2,2,2,2))

legend("bottomleft", legend=levels(data_practice$Diabetes_Over_Race), col=1:4, lty=c(1,1,1,1,2,2,2,2))
```

```{r}
cox_mod3<-coxph(Surv(AGE, exposure_birth, Mort_recode) ~ Diabetes_Over_Race + sex+ BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_recode+USBorn_Recode, data = data_practice)

summary(cox_mod3)

ggforest(cox_mod3, fontsize = 0.5)

data_practice%>%
  select(AGE, exposure_birth)%>%
  mutate(exposure_minus_age=exposure_birth-AGE)%>%
  arrange((exposure_minus_age))#There are people who die the same year as they NHIS-->Exposure time becomes zero
```

```{r}
data<-data%>%
  mutate(racea=as_factor(RACEA))%>%#When running code check sample size. Try to use raw
  filter(racea%in%c("White", "Asian Indian", "Filipino", "Chinese"))


table1(~as_factor(MORTUCODLD)|racea, data=data%>%filter(MORTSTAT==1))


table1(~factor(sex)+factor(Smoking_recode)+AGE+Education_recode+Earnings_recode+Insurance_recode+USBorn_Recode+DIABETICAGE2+Lifespan_Diabetic+factor(BMI_R_Cat)+factor(HYPERTENEV_recode) |racea2, data=data_table1)

```


```{r, table 1}
data_table1<-data_practice%>%
  mutate(DIABETICAGE2=ifelse(DIABETICAGE==96, NA, DIABETICAGE))%>%
  mutate(Lifespan_Diabetic=ifelse(
    Diabetes_Lifetime=="Diabetic"&MORTSTAT==1,
    exposure_birth,
    NA
  ))%>%
  mutate(HYPERTENEV_recode=case_when(#Go back and relevel for regression?
    HYPERTENEV==1~"No",
    HYPERTENEV==2~"Yes",
    HYPERTENEV%in%c(7,8,9)~"Unknown",
    TRUE~NA
  ))%>%
  mutate(Education_recode=factor(Education_recode, levels=c("Did Not Complete High School", "High School Grad","Some College", "4 years college/Bachelor's degree", "Post Bachelor", "Unknown")))%>%
  mutate(BMI_R_Cat=factor(BMI_R_Cat, levels=c("Underweight", "Normal Weight","Overweight", "Obese")))#Reordering levels





#table1(~ factor(sex) + age + factor(ulcer) + thickness | status, data=melanoma2)
table1(~factor(sex)+factor(Smoking_recode)+AGE+Education_recode+Earnings_recode+Insurance_recode+USBorn_Recode+DIABETICAGE2+Lifespan_Diabetic+factor(BMI_R_Cat)+factor(HYPERTENEV_recode)+Mortality_Status |racea2, data=data_table1)


```


```{r, table 2 Age Standardized Morality}
# data_practice%>%
#   select(racea2, Diabetes_Lifetime, AGE, MORTSTAT)%>%
#   mutate(age_group=casewhen(
#     
#     
#   ))




```
```{r}
head(data_practice)

```

```{r, weighting}
library(srvyr)


data_practice_weighted<-as_survey(data_practice,
     id=PSU,
     weight=PERWEIGHT,
     strata=STRATA,
     nest=TRUE)


data_practice_weighted
```


```{r, table 1 with weights}
# data_table1<-data_practice_weighted%>%
#   mutate(DIABETICAGE2=ifelse(DIABETICAGE==96, NA, DIABETICAGE))%>%
#   mutate(Lifespan_Diabetic=ifelse(
#     Diabetes_Lifetime=="Diabetic"&MORTSTAT==1,
#     exposure_birth,
#     NA
#   ))%>%
#   mutate(HYPERTENEV_recode=case_when(#Go back and relevel for regression?
#     HYPERTENEV==1~"No",
#     HYPERTENEV==2~"Yes",
#     HYPERTENEV%in%c(7,8,9)~"Unknown",
#     TRUE~NA
#   ))%>%
#   mutate(Education_recode=factor(Education_recode, levels=c("Did Not Complete High School", "High School Grad","Some College", "4 years college/Bachelor's degree", "Post Bachelor", "Unknown")))%>%
#   mutate(BMI_R_Cat=factor(BMI_R_Cat, levels=c("Underweight", "Normal Weight","Overweight", "Obese")))#Reordering levels
# 
# 
# table1_sum<-data_practice_weighted%>%
#   group_by(racea2) %>%
#   summarise(
#     proportion_female = survey_prop(sex == "Female"),
#     mean_age = survey_mean(Age)
#   )
# 
# table1(~proportion_female+ mean_age, data=table1_sum)
# 
# table1(~factor(sex)+factor(Smoking_recode)+AGE+Education_recode+Earnings_recode+Insurance_recode+USBorn_Recode+DIABETICAGE2+Lifespan_Diabetic+factor(BMI_R_Cat)+factor(HYPERTENEV_recode)+Mortality_Status |racea2, data=data_table1)

```
```{r, exporting figures}

library(grDevices)
png(file="myplot.png", width=1024, height=1024)
forrest_plot3
dev.off()

```

