---
title: "BenSzetoPostWeek6Analysis"
author: "Ben Szeto"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, loading libraries}
library(tidyverse)
library(knitr)
library(plotly)
library(ggeffects)
library(ggformula)
library(ipumsr)
```


```{r}


ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00029.xml")

data1 <- read_ipums_micro(ddi)

ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00027.xml")

data2 <- read_ipums_micro(ddi)

ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00030.xml")

data3 <- read_ipums_micro(ddi)

```

```{r, data merging}
data1<-data1%>%#Selecting variables of interest from data1
  select(NHISPID, DIABETICAGE, DIAYRSAGO)

data3<-data3%>%#Selecting variables of interest from data3
  select(NHISPID, MORTDODY, MORTWT, MORTSTAT)

data<-merge(data1, data2, by="NHISPID")
data<-merge(data, data3, by="NHISPID")

```


```{r}
data%>%
  mutate(racea=as_factor(RACEA))%>%
  mutate(mortstat=as_factor(MORTSTAT))%>%
  mutate(morthypr=MORTHYPR)%>%
  filter(racea%in%c("Chinese", "Asian Indian", "White", "Filipino"))%>%
  filter(!BMI==0)%>%
  filter(BMI<90)%>%
  filter(MORTELIG==1)%>%
   mutate(BMI_R_Cat=ifelse(racea=="White", 
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Whites
                                    BMI>=18.5 & BMI<25~"Normal Weight",
                                    BMI>=25 & BMI <30~"Overweight",
                                    BMI>=30~"Obese"),
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Asians (Considered all races not White)
                                    BMI>=18.5 & BMI<23~"Normal Weight",
                                    BMI>=23 & BMI <27.5~"Overweight",
                                    BMI>=27.5~"Obese")))#27.5 is obese for Asians

```

```{r}



```

Model 1: 