---
title: "Data Exploration Diabetes Cardiovascular Mortality"
author: "Ben Szeto"
date: "2024-06-27"
output: html_document
---

```{r setup, include=FALSE}
#
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(knitr)
library(plotly)
library(ggeffects)
library(ggformula)
```

```{r}
# NOTE: To load data, you must download both the extract's data and the DDI
# and also set the working directory to the folder with these files (or change the path below).

if (!require("ipumsr")) stop("Reading IPUMS data into R requires the ipumsr package. It can be installed using the following command: install.packages('ipumsr')")

ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00029.xml")
#/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00029.xml
#"C:\Users\bszet\OneDrive\Documents\Stanford Care Scholars\Diabetes Cardiovascular Outcomes\Data\nhis_00025.xml"

#"C:\Users\bszet\OneDrive\Documents\Stanford Care Scholars\Diabetes Cardiovascular Outcomes\Data\nhis_00025.dat"
data1 <- read_ipums_micro(ddi)

ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00027.xml")

#"C:\Users\bszet\OneDrive\Documents\Stanford Care Scholars\Diabetes Cardiovascular Outcomes\Data\nhis_00025.dat"
data2 <- read_ipums_micro(ddi)

data1<-data1%>%
  select(NHISHID, DIABETICAGE, DIAYRSAGO)

data<-merge(data1, data2, by="NHISHID")

data<-data%>%
  filter(AGE>=18)
```
```{r}
head(data)

```

```{r basic cleaning, go back to}
data<-data%>%
  mutate(racea=as_factor(RACEA))

```
```{r}
data%>%
  filter(DIABETICEV==2)%>%
  ggplot()+
  geom_bar(aes(x=DIAYRSAGO))


data%>%
  filter(DIABETICEV==2)%>%
  count(DIAYRSAGO)
```

```{r, DIAYRSAGO, doesn't have values that arent avaliable in DIABETICAGE}
data%>%
  select(DIABETICAGE, DIAYRSAGO)%>%
  filter(DIABETICAGE==96)%>%
  na.omit(DIAYRSAGO)%>%
  filter(!DIAYRSAGO==96)
```

```{r, counting number of individuals eligible for exposure time for competing risk analysis}

data%>%
  filter(DIABETICEV==2)%>%
  filter(racea%in%c("Chinese", "Asian Indian", "White", "Filipino"))%>%
  filter(DIABETICAGE<85)%>%
  filter(MORTELIG==1)%>%
  filter(!BMI==0)%>%
  filter(BMI<90)%>%
  group_by(racea)%>%
  count()


data%>%
  filter(DIABETICEV==2)%>%
  filter(racea%in%c("Chinese", "Asian Indian", "White", "Filipino"))%>%
  filter(DIABETICAGE<85)%>%
  filter(!BMI==0)%>%
  filter(BMI<90)%>%
  group_by(racea)%>%
  count()


data%>%
  filter(DIABETICEV==2)%>%
  filter(racea%in%c("Chinese"))%>%
  filter(DIABETICAGE<85)%>%
  filter(!BMI==0)%>%
   filter(!MORTELIG==1)%>%
  filter(BMI<90)%>%
  group_by(racea)


data%>%
  filter(DIABETICEV==2)%>%
  filter(racea%in%c("Chinese", "Asian Indian", "White", "Filipino"))%>%
  filter(DIABETICAGE<85)%>%
  filter(!BMI==0)%>%
   filter(MORTELIG==1)%>%
  filter(!MORTUCODLD==96)%>%
  filter(BMI<90)%>%
  group_by(racea)%>%
  count()

data%>%
  filter(DIABETICEV==2)%>%
  filter(racea%in%c("Chinese", "Asian Indian", "White", "Filipino"))%>%
  filter(MORTELIG==1)%>%
  group_by(racea)%>%
  count()

#Linear Interpolation
  
```
```{r}
data%>%
  filter(DIABETICEV==2)%>%
  filter(AGE>=18)%>%
  filter(racea%in%c("Chinese", "White"))%>%
  filter(DIABETICAGE<85)%>%
  filter(!BMI==0)%>%
   filter(MORTELIG==1)%>%
  mutate(NIU_Und=ifelse(MORTUCODLD==96, "Not in universe", "In Universe"))%>%
  filter(BMI<90)%>%
  group_by(NIU_Und, racea)%>%
  summarize(
    mean(AGE),
    n(),
    mean(DIABETICAGE)
  )



```

```{r}
set.seed(100)
data10k<-data%>%sample_n(10000)#Taking 10,000 random rows from data

```

```{r}
data10k%>% #Note this is from the random sample data so there may be things missing from the population
  lapply(unique)
```



Calculating Length Of Diabetes
Age of Diagnosis-->Calculate date relative to survey year--> Use mortality date --> Length diagnosed with diabetes (exposure time)

```{r, bmi category by race coded as BMI_R_Cat}

#Asian BMI cutoffs:#via WHO

#18.5–22.9 Normal

#23–27.5 kg/m2 (overweight)

#≥27.5 kg/m2 (obese)

#White BMI Cutoffs

# Underweight: Less than 18.5
# Healthy weight: 18.5–24.9
# Overweight: 25.0–29.9
# Obese: 30.0 or higher 



data<-data%>%
  filter(racea%in%c("White", "Asian Indian", "Filipino", "Chinese"))%>%
  mutate(BMI_R_Cat=ifelse(racea=="White", 
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Whites
                                    BMI>=18.5 & BMI<25~"Normal Weight",
                                    BMI>=25 & BMI <30~"Overweight",
                                    BMI>=30~"Obese"),
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Asians (Considered all races not White)
                                    BMI>=18.5 & BMI<23~"Normal Weight",
                                    BMI>=23 & BMI <27.5~"Overweight",
                                    BMI>=27.5~"Obese")))#27.5 is obese for Asians




                                    
```

```{r, creating exposure time variable}

data%>%
  select(YEAR)%>%
  mutate(DIABETICAGE=sample(1:30, n(), replace=TRUE))%>%#Practice Column (delete when actually get the dataset)
  mutate(Death_Year=sample(2000:2019, n(), replace=TRUE))%>%#Practice Column (delete when actually get the dataset)
  mutate(Years_Diabetes_pre=AGE-DIABETICAGE)%>%#calulating the year they were first diagnosed with diabetes
  mutate(Diabetes_Exposure=Death_Year-YEAR+Year_Diabetes_pre)#Calculating years they had diabetes

```



```{r}

#Counting number of levels for each variable
data%>% 
  sapply(function(x) length(unique(x)))

```

```{r}
head(data10k)

nrow(data10k)

table(data10k$SEX)
table(data10k$SEX)
table(data10k$RACEA)

nrow(data10k%>%filter(BMICALC==0))
nrow(data10k%>%filter(BMI==0))



data10k%>% #Checking distribution of BMI CALC; How many 0 and 996?
  mutate(BMI_Terms=ifelse(!BMICALC %in% c(0,996), "Within Range", BMICALC))%>%
  group_by(BMI_Terms)%>%
  summarize(
    n()
  )

data10k%>% #What does BMI do when BMI CALC is 996
  filter(BMICALC==996)%>%
  select(BMICALC, BMI,HEIGHT, WEIGHT)%>%
  arrange(desc(BMI))

```

```{r}
table(as_factor(data10k$USBORN))

```

```{r}
# data%>%
#   group_by(DIAB)


```

```{r}


#Distribution of BMICALC
# plotly::ggplotly(
data10k%>%
  ggplot(aes(x=BMICALC))+
  geom_histogram(binwidth = 1)
# )

data10k%>% #checking normality of BMICALC removing 0 and 996
  filter(!BMICALC %in% c(0, 996))%>%
  ggplot(aes(sample=BMICALC))+
  geom_qq()+
  geom_qq_line()

data10k%>% #checking normality of BMICALC removing 0 and 996
  filter(!BMICALC %in% c(0, 996))%>%
  ggplot(aes(x=BMICALC))+
  geom_histogram()



```

```{r}
library(corrplot)
cordata<-data10k%>%
  select(YEAR, AGE, SEX, MARSTCUR, RACEA, HISPYN, USBORN, EDUCREC2, EMPSTAT, POORYN, EARNINGS, OWNERSHIP, BMICALC, HEIGHT, WEIGHT, CHEARTDIEV, DIABETICEV, HEARTATTEV, HEARTCONEV, STROKEV, ALCSTAT1, SMOKESTATUS2, MOD10DMIN)
cordata_cor<-cor(cordata)


cordata_cor
corrplot(cordata_cor)
```

```{r prevalences of diseases}

# 
#   pivot_longer(
#     NHISHID,
#     names_to="Variable",
#     values_to="Level"
#   )

```

```{r}
library(janitor)


```

##Data Processing/Intial Univariate Analysis

```{r}
race_sub_data<-data%>%
  mutate(racea=as_factor(RACEA))#%>%
  #filter(racea%in%c("White", "Filipino", "Chinese", "Asian Indian", "Korean", "Vietnamese", "Japanese", "Pacific Islander"))

data.frame(table(race_sub_data$racea))%>%#Freq table of different Asian Races. As you can see only Filipino, Chinese, Asian Indian. Remove above # to see more
  arrange(desc(Freq))

```

```{r}

data10k<-data10k%>%#New variable called sex based on SEX variable
  mutate(sex=case_when(SEX==1~"male",
                       SEX==2~"female",
                       SEX%in%c(7,8,9)~"Unknown")#Single value for all reason unknown
         )
data10k%>%#bar plot for sex
  ggplot(aes(x=sex))+
  geom_bar()

data10k$RACEA2<-as_factor(data10k$RACEA)

data10k<-data10k%>%#new column that uses labels for race rather than code
  mutate(racea=as_factor(RACEA))

data10k%>% #Race bar plot
   ggplot(aes(x=racea))+
  geom_bar()


data.frame(prop.table(table(data10k$racea))*100)%>%rename(Percent=Freq)%>%arrange(desc(Percent)) # GO BACK AND TRY TO DO W/ JANITOR PACKAGE WITH LAPPLY


```

```{r, BMI shit}
#Distribution of BMI


# data10k%>%
#   ggplot(aes(x=BMI))+
#   geom_histogram(binwidth = 1)

data%>%
  select(BMI, BMICALC)%>%
  filter(!BMICALC==996)%>%
  filter(!BMI==0)%>%
  filter(!BMI>98)%>%
  filter(!BMI-BMICALC>1)%>%#Testing to see if they are all close in value
  ggplot()+
  geom_histogram(aes(x=BMI))#Distribution of BMI


data%>%#Determining number of BMI values we have for each race
  filter(!BMICALC==996)%>%
  filter(!BMI==0)%>%
  filter(!BMI>98)%>%
  filter(!BMI-BMICALC>1)%>%
  mutate(racea=as_factor(RACEA))%>%
  filter(racea%in%c("White", "Chinese", "Filipino", "Asian Indian"))%>%
  group_by(racea)%>%
  summarize(
    n(),
    mean(BMI),
    sd(BMI)
  )
```

```{r, looking into creating composite}


data%>%
  select(CHEARTDIEV, CONGHARTEV, HEARTATTEV, HEARTCONEV, HYPERTENEV, STROKEV)%>% #Columns you want to make a frequency table for
  lapply(as_factor)%>%
  lapply(table)%>%
  as.data.frame()

data%>%
  select(CHEARTDIEV, CONGHARTEV, HEARTATTEV, HEARTCONEV, HYPERTENEV, STROKEV)%>%#need to make a way to ignore missing/unknown
  filter(across(c(CHEARTDIEV, CONGHARTEV, HEARTATTEV, HEARTCONEV, HYPERTENEV, STROKEV), ~ . %in% c(1, 2)))%>%#There are now observations with zero not in universe values
  mutate(sum_disease=(CHEARTDIEV+CONGHARTEV+HEARTATTEV+HEARTCONEV+HYPERTENEV+STROKEV))#%>%
  # filter(sum_disease>0)%>%
  # ggplot(aes(x=sum_disease))+
  # geom_boxplot()



```

```{r, outcomes by year exploration}
Value_Each_Year_fig<-function(variable, dataset){#Creating function that can be used on all of the variables to make figures
  dataset%>%
    group_by(YEAR, {{variable}})%>%
    summarise(
      count=n()
    )%>%
    ungroup({{variable}})%>%
    mutate(proportion=count/sum(count))%>%
    ungroup()%>%
    ggplot(aes(x=YEAR, y=proportion, fill=as_factor({{variable}})))+
    geom_bar(stat="identity", position="dodge")

}


Value_Each_Year<-function(variable, dataset){#Creating function that can be used on all of the variables to make tables
  dataset%>%
    group_by(YEAR, {{variable}})%>%
    summarise(
      count=n()
    )%>%
    ungroup({{variable}})%>%
    mutate(proportion=sprintf("%.4f%%", count/sum(count)*100))
}

#making the tables
Value_Each_Year(CHEARTDIEV, data)
Value_Each_Year(CONGHARTEV, data)
Value_Each_Year(HEARTATTEV, data)
Value_Each_Year(HYPERTENEV, data)
Value_Each_Year(STROKEV, data)

#making the figures
Value_Each_Year_fig(CHEARTDIEV, data)
Value_Each_Year_fig(CONGHARTEV, data)
Value_Each_Year_fig(HEARTATTEV, data)
Value_Each_Year_fig(HYPERTENEV, data)
Value_Each_Year_fig(STROKEV, data)


Value_Each_Year(EMPSTAT, data)
Value_Each_Year_fig(EMPSTAT, data)
```

```{r, mortality data analysis}
#creating reference for data set called mortality_data_ref
mort_data_explore<-data%>%
  select(MORTELIG, MORTUCODLD, MORTWT, MORTDIAB, MORTHYPR, MORTWTSA)%>%
  lapply(as_factor)
```

```{r}

data%>%
  ggplot()+
  geom_bar(aes(x=as_factor(MORTUCODLD)))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))



data%>%
  mutate(racea=as_factor(RACEA))%>%
  filter(racea%in%c("Filipino", "Chinese", "Asian Indian"))%>%
  filter(!MORTUCODLD==96)%>%#filtering out NIU to make easier to read
  ggplot(aes(x=as_factor(MORTUCODLD), fill=racea))+
  geom_bar(position="dodge")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))




```

```{r, mortality data}
data%>%#Counting number of observations for each race for mortality data
  filter(MORTELIG==1)%>%
  filter(racea%in%c("White", "Chinese", "Asian Indian", "Filipino"))%>%
  group_by(racea)%>%
  count()

data%>%#Counting number of observations for each race for mortality data DIABETICS ONLY
  filter(MORTELIG==1)%>%
  filter(racea%in%c("White", "Chinese", "Asian Indian", "Filipino"))%>%
  filter(DIABETICEV%in%c(2,3))%>%#Filter if they have diabetes or borderline
  group_by(racea)%>%
  count()


data%>%
  select(MORTELIG, MORTUCODLD, MORTDIAB, MORTHYPR)%>%
  lapply(unique)

data<-data%>%
  mutate(CVDM=ifelse(MORTUCODLD%in%c(1, 5),1,0))#New column called CVDM for individuals who die from Disease of Heart or Cardiovascular disease

```

Model Practice

```{r}
table(data$CHEARTDIEV)
unique(data$CHEARTDIEV)
```

```{r}

CHEARTDIEV_data<-data%>%
  filter(CHEARTDIEV%in%c(1,2))%>%
  mutate(CHEARTDIEV_binary=case_when(CHEARTDIEV==1~0,
                                     CHEARTDIEV==2~1))%>%
  mutate(racea=as_factor(RACEA))%>%
  filter(racea%in%c("White", "Filipino", "Chinese", "Asian Indian"))

table(CHEARTDIEV_data$CHEARTDIEV_binary)

CHEARTDIEV_glm<-glm(CHEARTDIEV_binary~BMI+racea+BMI:racea, data=CHEARTDIEV_data, family="binomial")

summary(CHEARTDIEV_glm)#base case is white with 0 BMI

#Testing residuals

CHEARTDIEV_aug<-broom::augment(CHEARTDIEV_glm,CHEARTDIEV_data)%>%#augment function from the broom package NOT generics
  dplyr::mutate(.resp.resid=resid(CHEARTDIEV_glm, type="response"))

arm::binnedplot(CHEARTDIEV_aug$BMI, CHEARTDIEV_aug$.resp.resid, col.int = NULL)#Clear trend need to apply transformation



CHEARTDIEV_bmi <- ggpredict(CHEARTDIEV_glm, terms = c("BMI", "racea"))

plot(CHEARTDIEV_bmi)#Be sure to limit x axis domain

```

```{r, Model 1:  Cardiovascular death only for diabetics}

data_mod1<-data%>%
  filter(racea%in%c("White", "Chinese", "Filipino", "Asian Indian"))%>%
  filter(!MORTUCODLD==96)%>%#Removing NIU values
  filter(DIABETICEV%in%c(2,3))%>%#Diabetic or borderline
  filter(!BMI==0)%>%#Removing extraneous BMI values if present
  filter(!BMI>98)%>%
  mutate(sex=as_factor(SEX))%>%
  filter(sex%in%c("Male", "Female"))

mod1_glm<-glm(CVDM~BMI+racea+BMI:racea+sex, data=data_mod1, family="binomial")


summary(mod1_glm)


mod1_aug<-broom::augment(mod1_glm,data_mod1)%>%#augment function from the broom package NOT generics
  dplyr::mutate(.resp.resid=resid(mod1_glm, type="response"))

arm::binnedplot(mod1_aug$BMI, mod1_aug$.resp.resid, col.int = NULL)

mod1_pred <- ggpredict(mod1_glm, terms = c("BMI", "racea"))

plot(mod1_pred)#Be sure to limit x axis domain

library(datawizard)
ggpredict(mod1_glm, terms = c("BMI", "racea"))

#Do cox proportional hazard model
#Poisson regression

#Try to account for if they die of something else, code for that
#competing risk analysis
#either died from CVD, died from other, or alive
#UCLA OARC- Resource for methods/code
#https://www.nature.com/articles/1705727
```

```{r, looking into BMI and the development of diabetes for different groups}

data_diab<-data%>%
  filter(racea%in%c("White", "Chinese", "Filipino", "Asian Indian"))%>%
  filter(!MORTUCODLD==96)%>%#Removing NIU values
  filter(DIABETICEV%in%c(1,2,3))%>%
  mutate(Diab_bord=ifelse(DIABETICEV%in%c(2,3),1,0))%>%#Diabetic or borderline
  filter(!BMI==0)%>%#Removing extraneous BMI values if present
  filter(!BMI>98)%>%
  mutate(sex=as_factor(SEX))%>%
  filter(sex%in%c("Male", "Female"))

data_diab%>%
  select(DIABETICEV, Diab_bord)

diab_glm<-glm(Diab_bord~BMI+racea+BMI:racea+sex, data=data_diab, family="binomial")


summary(diab_glm)


diab_aug<-broom::augment(diab_glm,data_diab)%>%#augment function from the broom package NOT generics
  dplyr::mutate(.resp.resid=resid(diab_glm, type="response"))

arm::binnedplot(diab_aug$BMI, diab_aug$.resp.resid, col.int = NULL)#Clear trend need to apply transformation

diab_pred <- ggpredict(diab_glm, terms = c("BMI", "racea"))

plot(diab_pred)#Be sure to limit x axis domain


library(datawizard)
ggpredict(diab_glm, terms = c("BMI", "racea"))

```

#Competing Risk Analysis <file:///C:/Users/bszet/Downloads/Competing%20Risk%20Guide%20Paper.pdf> \# <https://cran.r-project.org/web/packages/casebase/vignettes/plotabsRisk.html> \#<https://www.publichealth.columbia.edu/research/population-health-methods/competing-risk-analysis> \#<https://www.youtube.com/watch?v=d5TwGaJZGSQ>

```{r}
library(cmprsk)

    #data prepping:
    
    #Going to use age as failure time for practice. This is not correct real world. 

data_cmprsk<-data%>%
  filter(racea%in%c("White", "Chinese", "Filipino", "Asian Indian"))%>%
  filter(!MORTUCODLD==96)%>%#Removing NIU values
  filter(DIABETICEV%in%c(1,2,3))%>%
  mutate(Diab_bord=ifelse(DIABETICEV%in%c(2),1,0))%>%#Diabetic
  filter(!BMI==0)%>%#Removing extraneous BMI values if present
  filter(!BMI>98)%>%
  mutate(sex=as_factor(SEX))%>%
  filter(sex%in%c("Male", "Female"))%>%
  select(AGE, CVDM, BMI, racea, sex, BMI_R_Cat)#Selecting columns

data_cmprsk

# head(data_cmprsk)
# 
# #Try treating BMI and Age as categorical variables: BMI standard thresholds (vary between White and Asians (27.5?)) + Age groups.
# #cumulative incidence rate
# 
 cuminc_test<-cuminc(ftime=data_cmprsk$AGE,fstatus=data_cmprsk$CVDM, group=data_cmprsk$racea)
 cuminc_test
 plot(cuminc_test)
# 
covariates_of_interest<-cbind(as_factor(data_cmprsk$BMI_R_Cat), as_factor(data_cmprsk$sex))
# 
# 
fine_gray_fit<-crr(data_cmprsk$AGE,data_cmprsk$CVDM,covariates_of_interest)
# 
# 
# summary(fine_gray_fit)

```

```{r}
#Calculating mortality rates

unique(data$MORTELIG)

table(as_factor(data$MORTELIG))
table(as_factor(data$MORTUCODLD))


data%>%
  filter(MORTUCODLD==96)%>%
  group_by(as_factor(MORTELIG))%>%
  count()



```
```{r}
data%>%
  filter(MORTELIG==1)


	⁃	```
