---
title: "Consolidating Code Dec 2024"
author: "Ben Szeto"
date: "2024-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, libraries}

library(tidyverse)
library(ipumsr)
library(survey)
library(srvyr)
library(table1)
```


```{r Ben Windows Paths}


ddi <- read_ipums_ddi("C:/Users/bszet/Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00029.xml")

data1 <- read_ipums_micro(ddi)

ddi <- read_ipums_ddi("C:/Users/bszet/Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00027.xml")

data2 <- read_ipums_micro(ddi)

ddi <- read_ipums_ddi("C:/Users/bszet/Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00030.xml")

data3 <- read_ipums_micro(ddi)

```


```{r Ben Mac Path}


# ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00029.xml")
# 
# data1 <- read_ipums_micro(ddi)
# 
# ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00027.xml")
# 
# data2 <- read_ipums_micro(ddi)
# 
# ddi <- read_ipums_ddi("/Users/benszeto/Library/CloudStorage/Box-Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00030.xml")
# 
# data3 <- read_ipums_micro(ddi)


```


```{r, data merging}
data1<-data1%>%#Selecting variables of interest from data1
  select(NHISPID, DIABETICAGE, DIAYRSAGO)

data3<-data3%>%#Selecting variables of interest from data3
  select(NHISPID, MORTDODY, MORTWT, MORTSTAT)

data<-merge(data1, data2, by="NHISPID")
data<-merge(data, data3, by="NHISPID")

```

```{r}
data<-data%>%
  mutate(Race=as_factor(RACEA))%>%#RACEA to Race
  mutate(mortstat=as_factor(MORTSTAT))%>%
  mutate(morthypr=as_factor(MORTHYPR))%>%
  mutate(sex=as_factor(SEX))

```


# ```{r}
# data%>%
#   group_by(Race, Diabetes_Lifetime, Mort_recode)%>%
#   count()
# 
# data%>%
#   select(Diabetes_Lifetime, DIABETICEV, MORTDIAB)%>%
#   filter(is.na(Diabetes_Lifetime))
# 
# unique(data$DIABETICEV)
# unique(data$MORTDIAB)
# ```

```{r, data filtering}
data<-data%>%
  filter(Race%in%c("Chinese", "Asian Indian", "White", "Filipino"))%>% #selecting Chinese, Asian Indian, Filipino, and White
  #filter(!BMI==0)%>% #filtering out extraneous BMIs #see section below
  #filter(BMI<90)%>%
  filter(MORTELIG==1)%>%#Make sure part of mortality data set, People who are less than 18 are not eligible
  filter(!(HISPYN==2 & Race=="White"))#Removing NHW
```


```{r, replacing BMI section data filtering}
data<-data%>%
  mutate(BMI=ifelse(BMI==0|BMI>90, "MISSING", BMI))
```

```{r}

data%>%
  select(HEIGHT,WEIGHT, BMICALC)%>%
  filter(BMICALC==0)

unique(data$EMPSTAT)
```
```{r}
unique(data$HINOTCOVE)
```




```{r}

data<-data%>%
  mutate(BMI_R_Cat=ifelse(BMI=="MISSING", "MISSING",ifelse(Race=="White", #Creating BMI Categorizations
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Whites
                                    BMI>=18.5 & BMI<25~"Normal Weight",
                                    BMI>=25 & BMI <30~"Overweight",
                                    BMI>=30~"Obese"),
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Asians (Considered all races not White)
                                    BMI>=18.5 & BMI<23~"Normal Weight",
                                    BMI>=23 & BMI <27.5~"Overweight",
                                    BMI>=27.5~"Obese"))))%>%#27.5 is obese for Asians
  mutate(Education_recode=case_when(#Education recoding
    EDUCREC2%in%c(10,20,30,31,32,40,41)~"Did Not Complete High School",
    EDUCREC2==42~"High School Grad",
    EDUCREC2%in%c(50,51,52,53)~"Some College",
    EDUCREC2==54~"4 years college/Bachelor's degree",
    EDUCREC2==60~"Post Bachelor",
    EDUCREC2%in%c(96, 97,98,99)~"Unknown",
    EDUCREC2==0~"NIU", 
    TRUE~"Check Again"
  ))%>%
  mutate(Smoking_recode=case_when(
    SMOKESTATUS2%in%c(10,11,12,13)~"Current Smoker",
    SMOKESTATUS2%in%c(20,40)~"Former Smoker",
    SMOKESTATUS2%in%c(30)~"Never Smoked",
    SMOKESTATUS2==90~"Unknown",
    TRUE~"Unknown"#Check this code later
  ))%>%
  mutate(Insurance_Status=case_when(
    HINOTCOVE==1~"Covered",
    HINOTCOVE==2~"Uncovered",
    HINOTCOVE%in%c(7,8,9)~"Unknown",
    TRUE~"Check Code"
  ))%>%
  mutate(USBorn_Recode=case_when(
         USBORN%in%c(10,11,12)~"Born Outside US",
         USBORN==20~"Born in US",
         TRUE~"MISSING"))%>%
  # move to factoring part of code mutate(USBorn_Recode=relevel(droplevels(as_factor(USBorn_Recode)), "Born in US"))
  mutate(Earnings_recode=as_factor(case_when(
    EARNINGS%in%c(0,97,98,99)~"NIU/Unknown",
    EARNINGS%in%c(1,2,3,4,5,6)~"Low Income ($1-$34,999)",
    EARNINGS%in%c(7,8,9,10)~"Middle Income($35,000-$74,999)",
    EARNINGS==11~"High Income(>$75,000)"
  )))%>%
  # Move down to facotring part mutate(Earnings_recode=factor(Earnings_recode, levels=c("Low Income ($1-$34,999)", "Middle Income($35,000-$74,999)","High Income(>$75,000)","NIU/Unknown"  )))%>%
  mutate(Diabetes_Lifetime=case_when(
    DIABETICEV==2|MORTDIAB==2~"Diabetic",
    DIABETICEV%in%c(0,7,8,9) & MORTDIAB==9~"Unknown/Not in Universe",
    TRUE~"Non-Diabetic"
  ))%>%
  mutate(Mort_recode=ifelse(MORTSTAT==1, TRUE, FALSE))%>%
  mutate(Mortality_Status=ifelse(MORTSTAT==1, "Presummed Dead", "Presummed Alive"))%>%#manually making the interaction term
  mutate(Diabetes_Lifetime_Race=as_factor(ifelse(
    Diabetes_Lifetime=="Diabetic",
    case_when(
      Race=="White"~"White Diabetic",
      Race=="Asian Indian"~"Asian Indian Diabetic",
      Race=="Filipino" ~"Filipino Diabetic",
      Race=="Chinese"~"Chinese Diabetic",
      TRUE~"Check Code"),
    "Non-Diabetic"
  )))%>%
  mutate(HYPERTENEV_recode=case_when(#Go back and relevel for regression?
    HYPERTENEV==1~"No",
    HYPERTENEV==2~"Yes",
    HYPERTENEV%in%c(7,8,9)~"Unknown",
    TRUE~NA
  ))%>%
  mutate(exposure_birth=ifelse(
    MORTSTAT==1,
    MORTDODY-YEAR+AGE,#If dead, time ends at year of death
    2019-YEAR+AGE#If alive or NIU, time ends at 2019
    ))%>%
  mutate(Lifespan_Diabetic=ifelse(
    Diabetes_Lifetime=="Diabetic"&MORTSTAT==1,
    exposure_birth,
    NA
  ))%>%
  mutate(Age_Diabetes_Diagnosis=ifelse(DIABETICAGE==96, NA, DIABETICAGE))%>%
  mutate(Diabetes_Over_Race=as_factor(ifelse(
    Diabetes_Lifetime=="Diabetic",
    case_when(
      Race=="White"~"White Diabetic",
      Race=="Asian Indian"~"Asian Indian Diabetic",
      Race=="Filipino" ~"Filipino Diabetic",
      Race=="Chinese"~"Chinese Diabetic",
      TRUE~"Check Code"),
    case_when(
      Race=="White"~"White Non-diabetic",
      Race=="Asian Indian"~"Asian Indian Non-diabetic",
      Race=="Filipino" ~"Filipino Non-diabetic",
      Race=="Chinese"~"Chinese Non-diabetic",
      TRUE~"Check Code")
  )))

```


```{r, leveling}
data<-data%>%
  mutate(Race=factor(droplevels(Race), c("White", "Chinese", "Filipino", "Asian Indian")))%>%
  mutate(Education_recode=factor(Education_recode, levels=c("High School Grad", "Did Not Complete High School","Some College", "4 years college/Bachelor's degree", "Post Bachelor", "Unknown")))%>%
  mutate(Smoking_recode=factor(Smoking_recode, c("Never Smoked", "Current Smoker", "Former Smoker", "Unknown")))%>%
  mutate(Insurance_Status=factor(Insurance_Status, c("Covered", "Uncovered", "Unknown")))%>%
  mutate(Earnings_recode=factor(Earnings_recode, c("Middle Income($35,000-$74,999)","Low Income ($1-$34,999)","High Income(>$75,000)", "NIU/Unknown")))%>%
  mutate(sex=factor(droplevels(sex), c("Male", "Female")))%>%
  mutate(Diabetes_Lifetime_Race=factor(Diabetes_Lifetime_Race, c("Non-Diabetic","White Diabetic", "Chinese Diabetic", "Filipino Diabetic","Asian Indian Diabetic")))%>%
  mutate(Diabetes_Lifetime=factor(Diabetes_Lifetime, c("Non-Diabetic", "Diabetic")))%>%#Removing people who are unknown for diabetes or not
  mutate(Diabetes_Over_Race=factor(Diabetes_Over_Race, c("White Non-diabetic","Asian Indian Non-diabetic", "Filipino Non-diabetic", "Chinese Non-diabetic","White Diabetic",  "Asian Indian Diabetic", "Filipino Diabetic", "Chinese Diabetic" )))%>%
  mutate(BMI_R_Cat=factor(BMI_R_Cat, c("Normal Weight", "Underweight", "Overweight", "Obese", "MISSING")))
  
  

levels(data$Race)
levels(data$Education_recode)
levels(data$Smoking_recode)
levels(data$Insurance_Status)
```

```{r, filtering out those NIU diabetes}


data<-data%>%
  filter(!is.na(Diabetes_Lifetime))

```


```{r, data weighting}

#Article comparing srvyr and survey: https://cran.r-project.org/web/packages/srvyr/vignettes/srvyr-vs-survey.html

data_weighted_survey<-as_survey(data,
                         id=PSU,
                         weight=PERWEIGHT,
                         strata=STRATA,
                         nest=TRUE)


data_weighted_svyr<-svydesign(id=~PSU,
          weights=~PERWEIGHT,
          strata=~STRATA,
          nest=TRUE,
          survey.lonely.psu="adjust",
          data=data)

```


```{r, association between missing BMI values and mortality status for dead people by race}

data%>%
  select(Race, Diabetes_Lifetime, BMI_R_Cat, Mort_recode)%>%
  filter(Diabetes_Lifetime=="Diabetic", Mort_recode==TRUE)%>%
  group_by(Race, BMI_R_Cat)%>%
  count()%>%
  ungroup()%>%
  group_by(Race)%>%
  mutate(percentage=n/sum(n))

```

STARTING DATA ANALYSIS HERE


```{r, analysis with omission}
data_analysis_omit<-data%>%
    select(exposure_birth, Mort_recode, Race, AGE, sex, Diabetes_Lifetime_Race, Diabetes_Lifetime, BMI_R_Cat, Education_recode, Earnings_recode, Smoking_recode, Insurance_Status, USBorn_Recode, PERWEIGHT, PSU, STRATA, MORTUCODLD)%>%
  mutate(study_exposure=exposure_birth-AGE)%>%
  filter(!study_exposure==0)

#miss_var_summary(data_analysis_omit)


data_weighted<-survey::svydesign(id=~PSU,
          weights=~PERWEIGHT,
          strata=~STRATA,
          nest=TRUE,
          survey.lonely.psu="adjust",
          data=data_analysis_omit)

cox_weighted<-svycoxph(Surv(study_exposure, Mort_recode==TRUE) ~ Race + AGE+Diabetes_Lifetime+sex+ BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_Status+USBorn_Recode, design = data_weighted)#Rework this #removing immigration makes races significant

summary(cox_weighted)



data_analysis_omit%>%
  group_by(Race, Diabetes_Lifetime, Mort_recode)%>%
  count()



car::vif(cox_weighted)
```
```{r, trying only looking at people with diabetes}
data_analysis_diabetes<-data_analysis_omit%>%
  #filter(Diabetes_Lifetime=="Non-Diabetic")%>%
  filter(Diabetes_Lifetime=="Diabetic")

data_analysis_diabetes%>%
  group_by(Race, Mort_recode)%>%
  count()


data_weighted<-survey::svydesign(id=~PSU,
          weights=~PERWEIGHT,
          #strata=~STRATA,
          nest=TRUE,
          survey.lonely.psu="adjust",
          data=data_analysis_diabetes)

cox_weighted_diabetes_w_nativity<-svycoxph(Surv(study_exposure, Mort_recode==TRUE) ~ Race + AGE+ sex+ Education_recode+Earnings_recode+Smoking_recode+Insurance_Status+BMI_R_Cat+USBorn_Recode, design = data_weighted)#Remove foreign born and asians lower risk


cox_weighted_diabetes<-svycoxph(Surv(study_exposure, Mort_recode==TRUE) ~ Race + AGE+ sex+ Education_recode+Earnings_recode+Smoking_recode+Insurance_Status+BMI_R_Cat, design = data_weighted)#Remove foreign born and asians lower risk


summary(cox_weighted_diabetes)
summary(cox_weighted_diabetes_w_nativity)

car::vif(cox_weighted_diabetes)
```

```{r}
data%>%
  group_by(Mort_recode, Diabetes_Lifetime)%>%
  count()



```

```{r, weighted proportion mortality}


#Old
table_1_weight_cat(data_weighted_survey, Mort_recode)



data_weighted_survey%>%
  group_by(Race,Diabetes_Lifetime, Mort_recode) %>%
  summarize(
    survey_total()
  )


data_analysis_omit%>%
  filter(Diabetes_Lifetime=="Diabetic")%>%
  summarize(
  mean(study_exposure)
  )
  


```


<!-- Trying to figure out how to do with MICE -->

<!-- ```{r} -->
<!-- library(VIM) -->
<!-- library(mice) -->
<!-- library(naniar) -->

<!-- ``` -->


<!-- ```{r, selecting variables for mice} -->

<!-- data_mice<-data%>% -->
<!--   select(exposure_birth, Mort_recode, Race, AGE, sex, Diabetes_Lifetime_Race, Diabetes_Lifetime, BMI, Education_recode, Earnings_recode, Smoking_recode, Insurance_Status, USBorn_Recode, PERWEIGHT, PSU, STRATA, MORTUCODLD) -->
<!-- ``` -->

<!-- ```{r, looking at missingness} -->
<!-- miss_var_summary(data_mice) -->
<!-- aggr(data_mice) -->
<!-- ``` -->
<!-- ```{r, mice} -->
<!-- data_mice_imp<-mice(data_mice, m=5)#took 30 mins+ to run DO NOT RUN AGAIN UNLESS U HAVE SPARE TIME -->
<!-- data_mice_imp_comp<- complete(data_mice_imp) -->
<!-- miss_var_summary(data_mice_imp_comp) -->
<!-- aggr(data_mice_imp_comp) -->



<!-- write.csv(data_mice_imp_comp, "Imputed_data", row.names = FALSE) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- read.csv("D:/DocumentsDisk2/StanfordCareScolarsLocal/CAREScholarsCVDLocal/Imputed_data") -->
<!-- ``` -->

<!-- ```{r} -->

<!-- data_mice%>% -->
<!--   group_by(BMI_R_Cat)%>% -->
<!--   count()%>% -->
<!--   ungroup()%>% -->
<!--   mutate(percentage=n/sum(n)) -->

<!-- data_mice%>% -->
<!--   group_by(BMI_R_Cat)%>% -->
<!--   na.omit(BMI_R_Cat)%>% -->
<!--   count()%>% -->
<!--   ungroup()%>% -->
<!--   mutate(percentage=n/sum(n)) -->

<!-- data_analysis_mice%>% -->
<!--   group_by(BMI_R_Cat)%>% -->
<!--   count()%>% -->
<!--   ungroup()%>% -->
<!--   mutate(percentage=n/sum(n)) -->



<!-- #Age -->

<!-- data_mice%>% -->
<!--   group_by(BMI_R_Cat, Mort_recode, Race)%>% -->
<!--   summarize( -->
<!--     mean(AGE)) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- data_analysis_mice<-data_mice_imp_comp%>% -->
<!--   select(exposure_birth, Mort_recode, Race, AGE, sex, Diabetes_Lifetime_Race, Diabetes_Lifetime,BMI, Education_recode, Earnings_recode, Smoking_recode, Insurance_Status, USBorn_Recode, PERWEIGHT, PSU, STRATA, MORTUCODLD)%>% -->
<!--   mutate(BMI_R_Cat=ifelse(Race=="White", #Creating BMI Categorizations -->
<!--                           case_when(BMI<18.5~"Underweight",#BMI thresholds for Whites -->
<!--                                     BMI>=18.5 & BMI<25~"Normal Weight", -->
<!--                                     BMI>=25 & BMI <30~"Overweight", -->
<!--                                     BMI>=30~"Obese"), -->
<!--                           case_when(BMI<18.5~"Underweight",#BMI thresholds for Asians (Considered all races not White) -->
<!--                                     BMI>=18.5 & BMI<23~"Normal Weight", -->
<!--                                     BMI>=23 & BMI <27.5~"Overweight", -->
<!--                                     BMI>=27.5~"Obese")))%>%#27.5 is obese for Asians -->
<!--   mutate(study_exposure=exposure_birth-AGE)%>% -->
<!--   filter(!study_exposure==0)%>% -->
<!--   na.omit() -->



<!-- table1(~study_exposure+exposure_birth+ Mort_recode+ Race+ AGE+ sex+ Diabetes_Lifetime_Race+ Diabetes_Lifetime+ BMI_R_Cat+ Education_recode+ Earnings_recode+ Smoking_recode+ Insurance_Status+ USBorn_Recode |Race, data=data_analysis_mice) -->


<!-- data_analysis_mice%>% -->
<!--   group_by(Race, Diabetes_Lifetime, Mort_recode)%>% -->
<!--   count() -->
<!-- ``` -->






<!-- ```{r, cox regression with imputed data} -->

<!-- data_input<-data_analysis_mice -->

<!-- data_weighted<-survey::svydesign(id=~PSU, -->
<!--           weights=~PERWEIGHT, -->
<!--           strata=~STRATA, -->
<!--           nest=TRUE, -->
<!--           survey.lonely.psu="adjust", -->
<!--           data=data_input) -->

<!-- cox_weighted<-svycoxph(Surv(study_exposure, Mort_recode==TRUE) ~ Race + AGE+Diabetes_Lifetime+Diabetes_Lifetime*Race+ sex+ BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_Status+USBorn_Recode, design = data_weighted) -->

<!-- summary(cox_weighted) -->



<!-- ``` -->


<!-- ```{r, trying to figure out nativity} -->
<!-- data_analysis_omit<-data%>% -->
<!--     select(exposure_birth, Mort_recode, Race, AGE, sex, Diabetes_Lifetime_Race, Diabetes_Lifetime, BMI_R_Cat, Education_recode, Earnings_recode, Smoking_recode, Insurance_Status, USBorn_Recode, PERWEIGHT, PSU, STRATA, MORTUCODLD)%>% -->
<!--   mutate(study_exposure=exposure_birth-AGE)%>% -->
<!--   filter(!study_exposure==0)%>% -->
<!--   filter(USBorn_Recode=="Born Outside US") -->
<!--   # filter(!Race=="White")%>% -->
<!--   # mutate(Race=factor(Race, c("Chinese", "Filipino", "Asian Indian"))) -->



<!-- data_weighted<-survey::svydesign(id=~PSU, -->
<!--           weights=~PERWEIGHT, -->
<!--           #strata=~STRATA, -->
<!--           nest=TRUE, -->
<!--           survey.lonely.psu="adjust", -->
<!--           data=data_analysis_omit) -->

<!-- cox_weighted<-svycoxph(Surv(study_exposure, Mort_recode==TRUE) ~Race+AGE+Diabetes_Lifetime+ sex+ BMI_R_Cat+Education_recode+Earnings_recode+Smoking_recode+Insurance_Status, design = data_weighted)#Rework this #removing immigration makes races significant -->

<!-- summary(cox_weighted) -->
<!-- ``` -->



