---
title: "Table1Bs"
author: "Ben Szeto"
date: "2024-08-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, loading libraries}
library(tidyverse)
library(knitr)
library(plotly)
library(ggeffects)
library(ggformula)
library(ipumsr)
library(survival)
library(survminer)
```


```{r}


ddi <- read_ipums_ddi("C:/Users/bszet/Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00029.xml")

data1 <- read_ipums_micro(ddi)

ddi <- read_ipums_ddi("C:/Users/bszet/Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00027.xml")

data2 <- read_ipums_micro(ddi)

ddi <- read_ipums_ddi("C:/Users/bszet/Box/CARE Scholars 2024 - Diabetes Mortality Project/Data and Code/nhis_00030.xml")

data3 <- read_ipums_micro(ddi)

```


```{r, data merging}
data1<-data1%>%#Selecting variables of interest from data1
  select(NHISPID, DIABETICAGE, DIAYRSAGO)

data3<-data3%>%#Selecting variables of interest from data3
  select(NHISPID, MORTDODY, MORTWT, MORTSTAT)

data<-merge(data1, data2, by="NHISPID")
data<-merge(data, data3, by="NHISPID")

```
```{r}
# data%>%
#   filter(!MORTDODY==9999)%>%
#   select(MORTDODY)%>%
#   arrange(desc(MORTDODY))

```


```{r, defining exposure time since DOB(This is what we use for expsoreu. underlying time scale cox)}
data<-data%>%
  mutate(exposure_birth=ifelse(
    MORTSTAT==1,
    MORTDODY-YEAR+AGE,#If dead, time ends at year of death
    2019-YEAR+AGE#If alive or NIU, time ends at 2019
    ))

```

```{r, defining exposure time since Diabetes Diagnosis}

data<-data%>%
  mutate(exposure_diabetes=ifelse(
    !DIABETICAGE==96 & !MORTDODY==9999,
    (AGE-DIABETICAGE)+(MORTDODY-YEAR),
    NA
  ))

```

```{r, data cleaning}
data<-data%>%
  mutate(racea=as_factor(RACEA))%>%
  mutate(mortstat=as_factor(MORTSTAT))%>%
  mutate(morthypr=as_factor(MORTHYPR))%>%
  mutate(sex=as_factor(SEX))%>%
  filter(racea%in%c("Chinese", "Asian Indian", "White", "Filipino"))%>% #selecting Chinese, Asian Indian, Filipino, and White
  filter(!BMI==0)%>% #filtering out extraneous BMIs
  filter(BMI<90)%>%
  filter(MORTELIG==1)%>%
  mutate(BMI_R_Cat=ifelse(racea=="White", 
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Whites
                                    BMI>=18.5 & BMI<25~"Normal Weight",
                                    BMI>=25 & BMI <30~"Overweight",
                                    BMI>=30~"Obese"),
                          case_when(BMI<18.5~"Underweight",#BMI thresholds for Asians (Considered all races not White)
                                    BMI>=18.5 & BMI<23~"Normal Weight",
                                    BMI>=23 & BMI <27.5~"Overweight",
                                    BMI>=27.5~"Obese")))#27.5 is obese for Asians
#mutate(CVD_MOR=ifelse(MORTUCODLD%in%c(1, 5), TRUE, FALSE))%>%
  
```

```{r recoding}


data<-data%>%#recoding education
  filter(!EDUCREC2==0)%>%
  mutate(Education_recode=case_when(
    EDUCREC2%in%c(10,20,30,31,32,40,41)~"Did Not Complete High School",
    EDUCREC2==42~"High School Grad",
    EDUCREC2%in%c(50,51,52,53)~"Some College",
    EDUCREC2==54~"4 years college/Bachelor's degree",
    EDUCREC2==60~"Post Bachelor",
    EDUCREC2%in%c(96, 97,98,99)~"Unknown",
    TRUE~"Check Again"
  ))



data<-data%>%
  mutate(Smoking_recode=case_when(
    SMOKESTATUS2%in%c(10,11,12,13)~"Current Smoker",
    SMOKESTATUS2%in%c(20,40)~"Former Smoker",
    SMOKESTATUS2%in%c(30)~"Never Smoked",
    SMOKESTATUS2==90~"Unknown",
    TRUE~"Check Code"
  ))


data<-data%>%
  mutate(Insurance_recode=case_when(
    HINOTCOVE==1~"Covered",
    HINOTCOVE==2~"Uncovered",
    HINOTCOVE%in%c(7,8,9)~"Unknown",
    TRUE~"Check Code"
    
  ))


data<-data%>%
  mutate(USBorn_Recode=case_when(
         USBORN%in%c(10,11,12)~"Born Outside US",
         USBORN==20~"Born in US"))%>%
  mutate(USBorn_Recode=relevel(droplevels(as_factor(USBorn_Recode)), "Born in US"))



data<-data%>%
  mutate(Earnings_recode=case_when(
    EARNINGS%in%c(0,97,98,99)~"NIU/Unknown",
    EARNINGS%in%c(1,2,3,4,5)~"Cat1",
    EARNINGS%in%c(5,6,7,8)~"Cat2",
    EARNINGS%in%c(9,10,11)~"Cat3"
  ))


data_practice<-data%>%
  mutate(Diabetes_Lifetime=case_when(
    DIABETICEV==2|MORTDIAB==2~"Diabetic",
    DIABETICEV%in%c(0,7,8,9) & MORTDIAB==9~"Unknown/Not in Universe",
    TRUE~"Non-Diabetic"
  ))%>%
  filter(!Diabetes_Lifetime=="Unknown/Not in Universe")%>%
  mutate(Diab_ACM=case_when(
    MORTSTAT==1&Diabetes_Lifetime=="Diabetic"~"Diabetic Death",
    MORTSTAT==2~"Assumed Alive",
    TRUE~"Other Death"
  ))%>%
  #select(MORTELIG, MORTSTAT, Diabetes_Lifetime, Diab_ACM)%>%
  mutate(Diab_ACM_binary=ifelse(Diab_ACM=="Diabetic Death", TRUE, FALSE))%>%#Diabetes and dead (not necessisarily underlying cause)
  mutate(Diab_Und_ACM=ifelse(
    MORTSTAT==1 & MORTDIAB==2,
    TRUE,
    FALSE
  ))

data_practice<-data_practice%>%
  mutate(sex=as_factor(SEX))%>%#removing extraneous levels
  mutate(sex=relevel(droplevels(sex), "Male"))%>%
  mutate(racea2=droplevels(racea))%>%
  mutate(racea2=relevel(racea2, "White"))%>%
  mutate(Smoking_recode=relevel(as_factor(Smoking_recode), "Never Smoked"))



data_practice<-data_practice%>%
  filter(HISPYN==1)
```

```{r}
library(table1)
```

```{r}
data_table1<-data_practice%>%
  mutate(DIABETICAGE2=ifelse(DIABETICAGE==96, NA, DIABETICAGE))%>%
  mutate(Lifespan_Diabetic=ifelse(
    Diabetes_Lifetime=="Diabetic"&MORTSTAT==1,
    exposure_birth,
    NA
  ))%>%
  mutate(HYPERTENEV_recode=case_when(#Go back and relevel for regression?
    HYPERTENEV==1~"No",
    HYPERTENEV==2~"Yes",
    HYPERTENEV%in%c(7,8,9)~"Unknown",
    TRUE~NA

  ))

#table1(~ factor(sex) + age + factor(ulcer) + thickness | status, data=melanoma2)
table1(~factor(sex)+factor(Smoking_recode)+AGE+Education_recode+Earnings_recode+Insurance_recode+USBorn_Recode+DIABETICAGE2+Lifespan_Diabetic+factor(BMI_R_Cat)+factor(HYPERTENEV_recode) |racea2, data=data_table1)


```

```{r}
data_practice%>%
  select(HYPERTENEV)%>%
  mutate(HYPERTENEV_recode=case_when(
    HYPERTENEV==1~"No",
    HYPERTENEV==2~"Yes",
    HYPERTENEV%in%c(7,8,9)~"Unknown",
    TRUE~NA

  ))%>%
  group_by(HYPERTENEV_recode)%>%
  count()
  



```