---
title: "Forrest Plots for Manuscript"
author: "Ben Szeto"
date: "2024-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)


```


```{r, forrest plot for individuals Total Population}

data_forest<-data.frame(
  Variable=c("Non-Hispanic White\n(Reference)", "Chinese", "Filipino", "Asian Indian"),
  Point_Estimate=c(1, 0.7188, 0.7763, 0.6575),
  Lower_Bound=c(1, 0.6227, 0.6874, 0.5305),
  Upper_Bound=c(1,0.8297, 0.8767, 0.8150)
)%>%
  mutate(Variable=factor(Variable, c("Asian Indian", "Filipino", "Chinese","Non-Hispanic White\n(Reference)")))


forest_plot_manual<-data_forest%>%
  ggplot(aes(y=Variable, x=Point_Estimate, xmin=Lower_Bound, xmax=Upper_Bound))+
  geom_point()+
  geom_errorbarh(height=0.2)+
  labs(x="Hazard Ratio", y="", title="Hazard Ratios for Asian Subgroups With Diabetes")+
  #scale_x_log10()+#do I need to make log scale?
  xlim(0,1.1)+
  geom_vline(xintercept=1, lty=2)+
  theme_minimal()+
  theme(axis.text=element_text(size=15))


forest_plot_manual






```


```{r, forest plot for total Population (added hazard ratios)}

data_forest<-data.frame(
  Variable=c("Non-Hispanic White\n(Reference)", "Chinese\n0.7188 [0.6227, 0.8297]", "Filipino\n0.7763 [0.6874, 0.8767]", "Asian Indian\n0.6575 [0.5305, 0.8150]"),
  Point_Estimate=c(1, 0.7188, 0.7763, 0.6575),
  Lower_Bound=c(1, 0.6227, 0.6874, 0.5305),
  Upper_Bound=c(1,0.8297, 0.8767, 0.8150)
)%>%
  mutate(Variable=factor(Variable, c("Asian Indian\n0.6575 [0.5305, 0.8150]", "Filipino\n0.7763 [0.6874, 0.8767]", "Chinese\n0.7188 [0.6227, 0.8297]","Non-Hispanic White\n(Reference)")))


forest_plot_manual<-data_forest%>%
  ggplot(aes(y=Variable, x=Point_Estimate, xmin=Lower_Bound, xmax=Upper_Bound))+
  geom_point()+
  geom_errorbarh(height=0.2)+
  labs(x="Hazard Ratio", y="", title="Hazard Ratios for Asian Subgroups Total Population")+
  #scale_x_log10()+#do I need to make log scale?
  geom_vline(xintercept=1, lty=2)+
  theme_minimal()+
  theme(axis.text=element_text(size=12), axis.text.y=element_text(colour="black"))+
  scale_x_continuous(breaks=seq(0,1,by=0.2), limits=c(0,1))



forest_plot_manual

```


```{r}


data_forest<-data.frame(
  Variable=c("NHW\n (Reference)", "Chinese", "Asian Indian", "Filipino", " ", "NHW Diabetes", "Chinese Diabetes", "Asian Indian Diabetes", "Filipino Diabetes"),
  Point_Estimate=c(1, 0.685862300, 0.592975260, 0.769339826, NA, 1.88086861, 1.6138903, 1.428759235, 1.494021085 ),
  Lower_Bound=c(1, 0.5880577655, 0.443903636,0.6661559135,NA , 1.843315293, 1.087904802, 0.6747849094, 1.072450859),
  Upper_Bound=c(1,0.783666834, 0.7420468847,0.8725237396, NA, 1.918421939 , 2.13987579, 2.182733561, 1.915591312)
)%>%
  mutate(Variable=factor(Variable, c("Filipino Diabetes", "Asian Indian Diabetes","Chinese Diabetes","NHW Diabetes",  " ",  "Filipino", "Asian Indian", "Chinese","NHW\n (Reference)")))


forest_plot_manual<-data_forest%>%
  ggplot(aes(y=Variable, x=Point_Estimate, xmin=Lower_Bound, xmax=Upper_Bound))+
  geom_point()+
  geom_errorbarh(height=0.2)+
  labs(x="Hazard Ratio", y="", title="Hazard Ratios for Asian Subgroups\nwith and without Diabetes")+
  #scale_x_log10()+#do I need to make log scale?
  xlim(0,3)+
  geom_vline(xintercept=1, lty=2)+
  theme_minimal()+
  theme(axis.text=element_text(size=15))


forest_plot_manual

```
```{r, w nativity}

data_forest<-data.frame(
  Variable=c("Non-Hispanic White\n(Reference)", "Chinese\n0.83 [0.61, 1.13]", "Filipino\n0.85 [0.66, 1.10]", "Asian Indian\n0.80 [0.67, 0.94]"),
  Point_Estimate=c(1, 0.83, 0.85, 0.80),
  Lower_Bound=c(1, 0.61, 0.66, 0.67),
  Upper_Bound=c(1,1.13, 1.10, 0.94)
)%>%
  mutate(Variable=factor(Variable, c("Asian Indian\n0.80 [0.67, 0.94]", "Filipino\n0.85 [0.66, 1.10]", "Chinese\n0.83 [0.61, 1.13]","Non-Hispanic White\n(Reference)")))


forest_plot_manual<-data_forest%>%
  ggplot(aes(y=Variable, x=Point_Estimate, xmin=Lower_Bound, xmax=Upper_Bound))+
  geom_point()+
  geom_errorbarh(height=0.2)+
  labs(x="Hazard Ratio", y="", title="Hazard Ratios for Asian subgroups\nIncluding Nativity")+
  #scale_x_log10()+#do I need to make log scale?
  geom_vline(xintercept=1, lty=2)+
  theme_minimal()+
  theme(axis.text=element_text(size=12), axis.text.y=element_text(colour="black"))+
  scale_x_continuous(breaks=seq(0,1,by=0.25), limits=c(0,1.25))



forest_plot_manual

```


```{r, nativity status}
data_forest<-data.frame(
  Variable=c("Born in US\n(Reference)", "Born Outside US\n0.81 [0.74, 0.89]"),
  Point_Estimate=c(1, 0.81),
  Lower_Bound=c(1, 0.74),
  Upper_Bound=c(1,0.89)
)%>%
  mutate(Variable=factor(Variable, c("Born Outside US\n0.81 [0.74, 0.89]", "Born in US\n(Reference)")))


forest_plot_manual<-data_forest%>%
  ggplot(aes(y=Variable, x=Point_Estimate, xmin=Lower_Bound, xmax=Upper_Bound))+
  geom_point()+
  geom_errorbarh(height=0.2)+
  labs(x="Hazard Ratio", y="", title="Hazard Ratios by Nativity Status")+
  #scale_x_log10()+#do I need to make log scale?
  geom_vline(xintercept=1, lty=2)+
  theme_minimal()+
  theme(axis.text=element_text(size=12), axis.text.y=element_text(colour="black"))+
  scale_x_continuous(breaks=seq(0,1,by=0.25), limits=c(0,1.25))



forest_plot_manual

```

```{r, w/o nativity}

data_forest<-data.frame(
  Variable=c("Non-Hispanic White\n(Reference)", "Chinese\n0.71 [0.54, 0.94]", "Filipino\n0.74  [0.58, 0.93]", "Asian Indian\n0.65 [0.51, 0.84]"),
  Point_Estimate=c(1, 0.71, 0.74, 0.65),
  Lower_Bound=c(1, 0.54, 0.58, 0.51),
  Upper_Bound=c(1,0.94, 0.93, 0.84)
)%>%
  mutate(Variable=factor(Variable, c("Asian Indian\n0.65 [0.51, 0.84]", "Filipino\n0.74  [0.58, 0.93]", "Chinese\n0.71 [0.54, 0.94]","Non-Hispanic White\n(Reference)")))


forest_plot_manual<-data_forest%>%
  ggplot(aes(y=Variable, x=Point_Estimate, xmin=Lower_Bound, xmax=Upper_Bound))+
  geom_point()+
  geom_errorbarh(height=0.2)+
  labs(x="Hazard Ratio", y="", title="Hazard Ratios for Asian subgroups\nOmitting Nativity")+
  #scale_x_log10()+#do I need to make log scale?
  geom_vline(xintercept=1, lty=2)+
  theme_minimal()+
  theme(axis.text=element_text(size=12), axis.text.y=element_text(colour="black"))+
  scale_x_continuous(breaks=seq(0,1,by=0.25), limits=c(0,1.25))



forest_plot_manual

```


```{r, visualizations for poster}

data_forest<-data.frame(
  Variable=c("Low Income ($1-$34,999)\n1.20(1.00, 1.44)", "Middle Income ($35,000-$74,999)\n(Reference)", "High Income (>$75,000)\n0.88 (0.76, 1.01)", "Did Not Complete High School\n1.15 (1.09, 1.20)", "High School\n(Reference)", "Some College\n1.00 (0.97, 1.02)", "4 Year College/Bachelor’s Degree\n0.88 (0.81, 0.95)", "Post Bachelor\n0.84 (0.82, 0.86)", "Insured\n(Reference)", "Uninsured\n1.17 (1.04, 1.31)"),
  Point_Estimate=c(1.20, 1, 0.88, 1.15, 1, 1.00, 0.88, 0.84, 1, 1.17),
  Lower_Bound=c(1.00,1.00, 0.76, 1.09, 1, 0.97, 0.81, 0.82, 1, 1.04),
  Upper_Bound=c(1.44,1.00, 1.01, 1.20, 1, 1.02, 0.95, 0.86, 1, 1.31)
)%>%
  mutate(Variable=factor(Variable, c("Uninsured\n1.17 (1.04, 1.31)", "Insured\n(Reference)", "Post Bachelor\n0.84 (0.82, 0.86)",  "4 Year College/Bachelor’s Degree\n0.88 (0.81, 0.95)","Some College\n1.00 (0.97, 1.02)", "High School\n(Reference)", "Did Not Complete High School\n1.15 (1.09, 1.20)",  "High Income (>$75,000)\n0.88 (0.76, 1.01)", "Middle Income ($35,000-$74,999)\n(Reference)","Low Income ($1-$34,999)\n1.20(1.00, 1.44)")))


forest_plot_manual<-data_forest%>%
  ggplot(aes(y=Variable, x=Point_Estimate, xmin=Lower_Bound, xmax=Upper_Bound))+
  geom_point()+
  geom_errorbarh(height=0.2)+
  labs(x="Hazard Ratio", y="", title="Risk of Mortality by Income, Education, and Nativity")+
  #scale_x_log10()+#do I need to make log scale?
  geom_vline(xintercept=1, lty=2)+
  theme_minimal()+
  theme(axis.text=element_text(size=12), axis.text.y=element_text(colour="black"))+
  scale_x_continuous(breaks=seq(0,1.5,by=0.25), limits=c(0.5,1.5))



forest_plot_manual

```
